### ISSUE TITLE
Specifying the `size` parameter for query_suggestion AppSearch method does not work.

### ISSUE THREAD

**Issue by matmunn** [elastic/enterprise-search-python#76]
I suspect this is at least partially related to https://github.com/elastic/enterprise-search-python/issues/27, but when specifying the `size` parameter when calling the AppSearch client's `query_suggestion` method returns an error from AppSearch.
The error returned is
```
{
  "errors": [
    "Size contains invalid option: must be an integer"
  ]
}
```

From what I can see, sending the parameters for the request in the request body works, while sending them via the query string doesn't.

**Comment by sethmlarson** [comment]
Hey! Sorry for the late response to this (my inbox moves too fast sometimes...) I believe this isn't an issue with the client but instead on the server-side. I've raised this with the App Search team and they're taking a look right now.

If you're looking for a work-around you can try calling the API manually with the transport:

```python
resp = client.app_search.transport.perform_request(
    "POST",
    "/api/as/v1/engines/example-engine/query_suggestion",
    body={
        "query": "text",
        "size": 10,
        "types": {
            "documents": {
                "fields": [
                    "title",
                ]
            }
        },
    },
)
```


I'll close this issue once the server team determines the bug is indeed server-side and we'll create a ticket to track elsewhere.

**Comment by sethmlarson** [comment]
App Search team is [considering this a bug](https://github.com/elastic/app-search-team/issues/2062), a fix will be available server-side in the near future. Thanks for reporting this!
